import { ValidationError } from './ValidationError.js';

export class AppRenderer {
  validate(bp) {
    if (!bp.brand?.name) {
      throw new ValidationError('App validation failed: blueprint.brand.name is missing.');
    }
    if (!bp.pages || !Array.isArray(bp.pages)) {
      throw new ValidationError('App validation failed: blueprint.pages is missing or not an array.');
    }
    if (!bp.theme?.colors) {
      throw new ValidationError('App validation failed: blueprint.theme.colors is missing.');
    }
  }

  render(bp, theme = 'modernDark') {
    this.validate(bp);

    const name = bp.brand.name;
    const pal = bp.theme.colors;
    const pages = bp.pages.map(p => {
      const pageName = String(p.name || 'Home').replace(/\s+/g, '');
      return {
        name: pageName,
        path: p.path || (pageName === 'Home' ? '/' : `/${pageName.toLowerCase()}`)
      };
    });

    const style = bp.theme.style || 'Modern';
    const navLinks = bp.navigation?.links || [];
    const tagline = bp.brand.tagline;
    const footerLinks = bp.footer?.links || [];

    const imports = pages
      .map(p => `import ${p.name}Page from './pages/${p.name}Page'`)
      .join('\n');

    const routes = pages
      .map(p => `          <Route path="${p.path}" element={<${p.name}Page />} />`)
      .join('\n');

    const homePage = pages.find(p => p.path === '/');
    const fallbackElement = homePage ? `<${homePage.name}Page />` : `<HomePage />`;

    return `import { BrowserRouter, Routes, Route } from 'react-router-dom'
import { ThemeProvider } from './theme/ThemeProvider'
import Navbar from './components/layout/Navbar'
import Footer from './components/layout/Footer'
${imports}
${!homePage ? "import HomePage from './pages/HomePage'" : ""}

/**
 * ${name}
 * Design style: ${style}
 * Theme: ${theme}
 * Generated by Getartifact — https://getartifact.dev
 */
export default function App() {
  return (
    <ThemeProvider initialTheme="${theme}">
      <BrowserRouter>
        <div
          className="min-h-screen"
          style={{ background: '${pal.background}', color: '${pal.text}', fontFamily: 'Inter, sans-serif' }}
        >
          <Navbar
            brand="${name}"
            links={${JSON.stringify(navLinks)}}
            primaryColor="${pal.primary}"
          />
          <main>
            <Routes>
${routes}
              <Route path="*" element={${fallbackElement}} />
            </Routes>
          </main>
          <Footer
            brand="${name}"
            tagline="${tagline || ''}"
            links={${JSON.stringify(footerLinks || [])}}
          />
        </div>
      </BrowserRouter>
    </ThemeProvider>
  )
}`;
  }
}
