// d:/ornitech-sample/3d-website/server/core/builder/WorkspaceBuilder.js
import fs from 'fs/promises';
import path from 'path';
import { logger } from '../logger.js';

class WorkspaceBuilder {
    constructor(buildDir, blueprint) {
        this.buildDir = buildDir;
        this.blueprint = blueprint;
    }

    async setup() {
        logger.info(`[WorkspaceBuilder] Setting up workspace at: ${this.buildDir}`);
        await this._createDirectoryStructure();
        await this._createBoilerplateFiles();
        logger.info('[WorkspaceBuilder] Workspace setup complete.');
    }

    async _createDirectoryStructure() {
        const dirs = [
            'src/app',
            'src/components',
            'src/layouts',
            'src/sections',
            'src/assets/images',
            'src/assets/fonts',
            'src/assets/models',
            'src/public',
            'src/styles',
            'src/hooks',
            'src/utils',
            'src/config'
        ];

        for (const dir of dirs) {
            await fs.mkdir(path.join(this.buildDir, dir), { recursive: true });
        }
    }

    async _createBoilerplateFiles() {
        const files = {
            '.gitignore': this._getGitignoreContent(),
            '.env.example': this._getEnvExampleContent(),
            'README.md': this._getReadmeContent(),
            'src/main.jsx': this._getMainJsxContent(),
            'index.html': this._getIndexHtmlContent(),
        };

        for (const [filePath, content] of Object.entries(files)) {
            await fs.writeFile(path.join(this.buildDir, filePath), content);
        }
    }

    _getGitignoreContent() {
        return `
# Dependencies
/node_modules
/dist

# Environment variables
.env
.env*.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# IDEs and editors
.vscode/
.idea/
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# Build artifacts
/build
/out

# Temporary files
.DS_Store
        `.trim();
    }

    _getEnvExampleContent() {
        return `
# Example environment variables
VITE_API_ENDPOINT=http://localhost:3001/api
        `.trim();
    }

    _getReadmeContent() {
        const projectName = this.blueprint.projectName || 'AI Generated Website';
        return `
# ${projectName}

This project was generated by the OrniTech AI Website Generator.

## Getting Started

1.  **Install dependencies:**
    \`\`\`bash
    npm install
    \`\`\`

2.  **Run the development server:**
    \`\`\`bash
    npm run dev
    \`\`\`

3.  **Build for production:**
    \`\`\`bash
    npm run build
    \`\`\`
        `.trim();
    }

    _getIndexHtmlContent() {
        const projectName = this.blueprint.projectName || 'AI Generated Website';
        return `<!doctype html>
<html lang="en">
    <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
    </head>
    <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
    </body>
</html>`;
    }

    _getMainJsxContent() {
        return `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './styles/index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
    <React.StrictMode>
    <App />
    </React.StrictMode>,
)`;
    }
}

export { WorkspaceBuilder };
