
class SceneComposer {
  /**
   * Assembles the final scene definition.
   * @param {object} blueprint - The Blueprint V3 object.
   * @param {object} scenePlan - The ScenePlan generated by ScenePlanner.
   * @param {object} assetManifest - The AssetManifest generated by AssetResolver.
   * @returns {object} The final SceneDefinition.
   */
  composeScene(blueprint, scenePlan, assetManifest) {
    if (!blueprint || !scenePlan || !assetManifest) {
      throw new Error('Blueprint, ScenePlan, and AssetManifest are required.');
    }

    const sceneDefinition = {
      version: '1.0',
      scene: {
        ...scenePlan,
        nodes: this.composeNodes(blueprint, assetManifest),
      },
      assets: assetManifest.assets,
    };

    return sceneDefinition;
  }

  /**
   * Composes the scene graph nodes from the blueprint components.
   * @param {object} blueprint - The blueprint object.
   * @param {object} assetManifest - The asset manifest.
   * @returns {object[]} An array of scene nodes.
   */
  composeNodes(blueprint, assetManifest) {
    let nodes = [];
    if (blueprint.sections) {
      for (const section of Object.values(blueprint.sections)) {
        if (section.components) {
          for (const component of Object.values(section.components)) {
            // Re-generate assetId to find it in the manifest
            const props = component.props || {};
            let assetId;
            if (props.modelSrc) assetId = this.generateAssetId(props.modelSrc);
            else if (props.imageSrc) assetId = this.generateAssetId(props.imageSrc);
            else if (props.fontFamily) assetId = this.generateAssetId(props.fontFamily);

            const node = this.createComponentNode(component, assetManifest, assetId);
            if (node) {
              nodes.push(node);
            }
          }
        }
      }
    }
    return nodes;
  }

  /**
   * Creates a scene node for a single component.
   * @param {object} component - The component from the blueprint.
   * @param {object} assetManifest - The asset manifest.
   * @param {string} assetId - The pre-calculated asset ID for the component's primary asset.
   * @returns {object|null} A scene node or null.
   */
  createComponentNode(component, assetManifest, assetId) {
      const node = {
          id: component.id,
          type: 'Group', // Default node type
          position: component.layout?.position || [0, 0, 0],
          rotation: component.layout?.rotation || [0, 0, 0],
          scale: component.layout?.scale || [1, 1, 1],
          children: [],
          properties: {},
      };

      const asset = assetManifest.assets[assetId];

      switch(component.type) {
          case 'Model':
              if (asset) {
                  node.children.push({
                      type: 'GLTF',
                      assetId: assetId,
                      uri: asset.uri
                  });
              }
              break;
          case 'Image':
              if(asset) {
                  node.type = 'Image';
                  node.assetId = assetId;
                  node.uri = asset.uri;
              }
              break;
          case 'Text':
              const fontAsset = assetManifest.assets[assetId];
              node.type = 'Text';
              node.properties = {
                  content: component.props.text,
                  fontAssetId: assetId,
                  fontUri: fontAsset ? fontAsset.uri : null,
                  color: component.props.color || '#000000'
              };
              break;
          default:
              // For other components or components without a primary asset
              break;
      }

      return node;
  }

    /**
     * Generates a deterministic ID for an asset based on its source.
     * (This is duplicated from AssetPlanner, in a real scenario it would be a shared utility)
     * @param {string} src - The source of the asset.
     * @returns {string} A unique ID.
     */
    generateAssetId(src) {
        let hash = 0;
        for (let i = 0; i < src.length; i++) {
            const char = src.charCodeAt(i);
            hash = (hash << 5) - hash + char;
            hash |= 0; // Convert to 32bit integer
        }
        return `asset_${Math.abs(hash).toString(16)}`;
    }
}

export default SceneComposer;
